import AakankshaMarketingMember from "../../../../assets/team/AakankshaMarketingMember.gif";
import AditiEVENTSMember from "../../../../assets/team/AditiEVENTSMember.gif";
import AniketCHAIRPERSON from "../../../../assets/team/AniketCHAIRPERSON.gif";
import AryaHEADSOCIALMEDIA from "../../../../assets/team/AryaHEADSOCIALMEDIA.gif";
import AtharwaPublicelationMember from "../../../../assets/team/AtharwaPublicelationMember.gif";
import AvaniEVENTSMember from "../../../../assets/team/AvaniEVENTSMember.gif";
import AyushTechnicalMember from "../../../../assets/team/AyushTechnicalMember.gif";
import HemantTechnicalMember from "../../../../assets/team/HemantTechnicalMember.gif";
import KartikHEADMARKETING from "../../../../assets/team/KartikHEADMARKETING.gif";
import KunalEVENTSMember from "../../../../assets/team/KunalEVENTSMember.gif";
import ParthInamdarHEADTECHNICAL from "../../../../assets/team/ParthInamdarHEADTECHNICAL.gif";
import ParthTechnicalMember from "../../../../assets/team/ParthTechnicalMember.gif";
import PradyumnSocialMediaMember from "../../../../assets/team/PradyumnSocialMediaMember.gif";
import PrajaktaHEADDESIGN from "../../../../assets/team/PrajaktaHEADDESIGN.gif";
import PratapDesignMember from "../../../../assets/team/PratapDesignMember.gif";
import PratikTechnicalMember from "../../../../assets/team/PratikTechnicalMember.gif";
import PriyeshPublicRelationMember from "../../../../assets/team/PriyeshPublicRelationMember.gif";
import PruthvirajsinghSocailMediaMember from "../../../../assets/team/PruthvirajsinghSocailMediaMember.gif";
import SakshiVICEHAIRPERSON from "../../../../assets/team/SakshiVICEHAIRPERSON.gif";
import ShashankHEADEVENTS from "../../../../assets/team/ShashankHEADEVENTS.gif";
import SuhasEVENTSMember from "../../../../assets/team/SuhasEVENTSMember.gif";
import SwetalMarketingMember from "../../../../assets/team/SwetalMarketingMember.gif";
import VivekEVENTSMember from "../../../../assets/team/VivekEVENTSMember.gif";
import SushrutHeadPR from "../../../../assets/team/SushrutHeadPR.JPG";
import SurajTechnical from "../../../../assets/team/SurajTechnical.jpg";
import SakshiPR from "../../../../assets/team/SakshiPR.jpg";
import AdityaMarketing from "../../../../assets/team/AdityaMarketing.jpg";
import ParminderKaur from "../../../../assets/team/ParminderKaur.jpeg";

const data = [
  {
    no: "0",
    name: "Parminder Kaur",
    designation: "Head, Training and Placement Cell",
    team: "TnP",
    contact: "9511248614",
    img: ParminderKaur,
  },
  {
    no: "1",
    name: "Aniket Chaudhari",
    designation: "President",
    team: "Head",
    contact: "9511248614",
    email: "aniketchuadhari303@gmail.com",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/aniket-chaudhari-801015217",
    github: "https://github.com/aniketchaudharicodes",
    twitter: "",
    instagram: "https://instagram.com/aniketchaudhari.eth",
    img: AniketCHAIRPERSON,
  },
  {
    no: "2",
    name: "Sakshi Bajaj",
    designation: "Vice President",
    team: "Head",
    contact: "7385051085",
    email: "sakshibajaj393@gmail.com",
    tshirt: "S",
    linkedin: "https://www.linkedin.com/in/sakshi-bajaj-501494216",
    github: "https://github.com/bajajsakshi738",
    twitter: "https://twitter.com/bajajsakshi_85",
    instagram: "https://instagram.com/iamsakshibajaj ",
    img: SakshiVICEHAIRPERSON,
  },
  {
    no: "3",
    name: "Parth Inamdar",
    designation: "Head",
    team: "Technical",
    contact: "8793928040",
    email: "parthinamdar1970@gmail.com",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/parth-inamdar-81481a21b/",
    github: "",
    twitter: "",
    instagram: "",
    img: ParthInamdarHEADTECHNICAL,
  },
  {
    no: "4",
    name: "Ayush Chaudhari ",
    designation: "Member",
    team: "Technical",
    contact: "9325898195",
    email: "ayushschaudhari1904@gmail.com",
    tshirt: "XL",
    linkedin: "https://www.linkedin.com/in/ayush-chaudhari-14981623b",
    github: "https://github.com/the-bokya",
    twitter: "",
    instagram: "https://www.instagram.com/thebokya/",
    img: AyushTechnicalMember,
  },
  {
    no: "5",
    name: "Parth Bhawar",
    designation: "Member",
    team: "Technical",
    contact: "9373097450",
    email: "parthmgmu@gmail.com",
    tshirt: "",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: ParthTechnicalMember,
  },
  {
    no: "6",
    name: "Hemant Singh Parmar",
    designation: "Member",
    team: "Technical",
    contact: "7559228490",
    email: "anmolpawar877@gmail.com",
    tshirt: "XL",
    linkedin: "https://www.linkedin.com/in/hemant-singh-parmar-b615a921a/",
    github: "https://github.com/hemant-code625",
    twitter: "https://twitter.com/ThisIs_Hemant",
    instagram: "https://www.instagram.com/its_hemantsig/",
    img: HemantTechnicalMember,
  },
  {
    no: "7",
    name: "Suraj Nagre",
    designation: "Member",
    team: "Technical",
    contact: "7558697774",
    email: "surajnagre30@gmail.com",
    tshirt: "XL",
    linkedin: "https://www.linkedin.com/in/suraj-nagre-836576214/",
    github: "https://github.com/kurai-sx",
    twitter: "https://twitter.com/Suraj_Nagre_",
    instagram: "https://www.instagram.com/kurai.sx/",
    img: SurajTechnical,
  },
  {
    no: "8",
    name: "Pratik Jadhav",
    designation: "Member",
    team: "Technical",
    contact: "9404730294",
    email: "j.pratik025@gmail.com",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/pratik-jadhav-44005a253/",
    github: "https://github.com/pratik50",
    twitter: "",
    instagram: "https://www.instagram.com/j_pratik99/",
    img: PratikTechnicalMember,
  },
  {
    no: "9",
    name: "Shashank Padhye",
    designation: "Head",
    team: "Events",
    contact: "9356425499",
    email: "shashankpadhye9@gmail.com",
    tshirt: "M",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: ShashankHEADEVENTS,
  },
  {
    no: "10",
    name: "Avani Pathak ",
    designation: "Member",
    team: "Events",
    contact: "9021999704",
    email: "pathakavani0226@gmail.com",
    tshirt: "L",
    linkedin: "https://www.linkedin.com/in/avani-pathak-5a131223b",
    github: "",
    twitter: "",
    instagram: "https://instagram.com/__avaanniii__",
    img: AvaniEVENTSMember,
  },
  {
    no: "11",
    name: "Vivek Ingle",
    designation: "Member",
    team: "Events",
    contact: "9529743301",
    email: "vivekingle315@gmail.com",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/inglevivek/",
    github: "",
    twitter: "",
    instagram: "https://www.instagram.com/thevivekingle/",
    img: VivekEVENTSMember,
  },
  {
    no: "12",
    name: "Suhas Magar",
    designation: "Member",
    team: "Events",
    contact: "7020463624",
    email: "suhasmagar273@gmail.com",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/suhas-magar-46685a229/",
    github: "",
    twitter: "",
    instagram: "https://www.instagram.com/suhas_m1/",
    img: SuhasEVENTSMember,
  },
  {
    no: "13",
    name: "Aditi Jadhav",
    designation: "Member",
    team: "Events",
    contact: "7773923224",
    email: "jadhavaditi126@gmail.com",
    tshirt: "S",
    linkedin: "https://www.linkedin.com/in/aditi-jadhav-818b1a256/",
    github: "",
    twitter: "",
    instagram: "",
    img: AditiEVENTSMember,
  },
  {
    no: "14",
    name: "Kunal Wagh",
    designation: "Member",
    team: "Events",
    contact: "9822634213",
    email: "kunalwagh282@gmail.com",
    tshirt: "M",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: KunalEVENTSMember,
  },
  {
    no: "15",
    name: "Prajakta Wakhare",
    designation: "Head",
    team: "Design",
    contact: "8055860877",
    email: "wakhareprajakta@gmail.com",
    tshirt: "S",
    linkedin: "https://www.linkedin.com/in/prajakta-wakhare-00595b222",
    github: "https://github.com/Prajakta-Wakhare",
    twitter: "",
    instagram: "https://instagram.com/praajakttaaa?utm_source=qr&igshid=MThlNWY1MzQwNA==",
    img: PrajaktaHEADDESIGN,
  },
  {
    no: "16",
    name: "pratap Pawar",
    designation: "Member",
    team: "Design",
    contact: "9309058717",
    email: "pratapsingh08pawar@gmail.com",
    tshirt: "",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: PratapDesignMember,
  },
  {
    no: "19",
    name: "Sushrut Lekurwale",
    designation: "Head",
    team: "Public Relations ",
    contact: "7768882081",
    email: "lekurwalesushrut@gmail.com",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/sushrut-lekurwale/",
    github: "https://github.com/sushrutlekurwale",
    twitter: "",
    instagram: "https://www.instagram.com/lekurwale_sushrut07/",
    img: SushrutHeadPR,
  },
  {
    no: "20",
    name: "Sakshi Akhare",
    designation: "Member",
    team: "Public Relations ",
    contact: "9921096415",
    email: "sakshiakhare17@gmail.com",
    tshirt: "S",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: SakshiPR,
  },
  {
    no: "21",
    name: "Atharva Raulwar",
    designation: "Member",
    team: "Public Relations ",
    contact: "7507975334",
    email: "atharvateamxtreme@gmail.com",
    tshirt: "",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: AtharwaPublicelationMember,
  },
  {
    no: "22",
    name: "Priyesh Sahijwani ",
    designation: "Member",
    team: "Public Relations ",
    contact: "9890532718",
    email: "priyeshsahijwani@gmail.com",
    tshirt: "",
    linkedin: "www.linkedin.com/in/priyesh-sahijwani",
    github: "https://github.com/priyesh-sahijwani",
    twitter: "",
    instagram: "https://instagram.com/priyesh_sahijwani",
    img: PriyeshPublicRelationMember,
  },
  {
    no: "23",
    name: "Arya Malode",
    designation: "Head",
    team: "Social Media",
    contact: "8767467058",
    email: "aryamalode17@gmail.com",
    tshirt: "XS",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: AryaHEADSOCIALMEDIA,
  },
  {
    no: "24",
    name: "Pruthavirajsingh Dulat",
    designation: "Member",
    team: "Social Media",
    contact: "8793879208",
    email: "pruthvirajytube@gmail.com",
    tshirt: "L",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: PruthvirajsinghSocailMediaMember,
  },
  {
    no: "25",
    name: "Pradyumn Bhanegaonkar ",
    designation: "Member",
    team: "Social Media",
    contact: "9422886711",
    email: "pradyumnbhanegaonkar@gmail.com",
    tshirt: "L",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: PradyumnSocialMediaMember,
  },
  {
    no: "26",
    name: "Kartik Mhaske",
    designation: "Head",
    team: "Marketing",
    contact: "9130373357",
    email: "Kartik69personal@gmail.com ",
    tshirt: "M",
    linkedin: "https://www.linkedin.com/in/kartik-mhaske-1b36a0200",
    github: "",
    twitter: "",
    instagram: "https://instagram.com/kartikmhaske_/",
    img: KartikHEADMARKETING,
  },
  {
    no: "27",
    name: "Swetal Matkar",
    designation: "Member",
    team: "Marketing",
    contact: "8007773577",
    email: "Matkarswetal@gmail.com",
    tshirt: "S",
    linkedin: "",
    github: "",
    twitter: "",
    instagram: "",
    img: SwetalMarketingMember,
  },
  {
    no: "28",
    name: "Aakanksha Kate",
    designation: "Member",
    team: "Marketing",
    contact: "9168839562",
    email: "aakankshakate29@gmail.com ",
    tshirt: "S",
    linkedin: "https://www.linkedin.com/in/aakanksha-kate-a90994258/",
    github: "",
    twitter: "",
    instagram: "https://www.instagram.com/itsme_ansha/",
    img: AakankshaMarketingMember,
  },
  {
    no: "29",
    name: "Aditya Isadkar",
    designation: "Member",
    team: "Marketing",
    contact: "9403412529",
    email: "adityaisadkar940@gmail.com",
    tshirt: "XL",
    linkedin: "https://www.linkedin.com/in/aditya-isadkar-b73a02258",
    github: "https://github.com/adityaisadkar",
    twitter: "https://twitter.com/adirocks940",
    instagram: "https://www.instagram.com/adi940rocks/",
    img: AdityaMarketing,
  },
];

export default data;
