import Aniket from "../../../../assets/images/teams/1.jpg";
import Sakshi from "../../../../assets/images/teams/ViceChair.jpg";
import Parth from "../../../../assets/images/teams/ParthInamdar.jpg";
// import Ayush from "../../../../assets/images/teams/DSC_4021.jpg";
import Hemant from "../../../../assets/images/teams/Hemant Singh Parmar.jpg";
import Suraj from "../../../../assets/images/teams/Snapchat-861277505.jpg";
import Pratik from "../../../../assets/images/teams/Pratik Jadhav.jpg";
import ParthBhawar from "../../../../assets/images/teams/Parth R. Bhawar.png";
// import Shashank from "../../../../assets/images/teams/IMG_2843.jpg";
import Avani from "../../../../assets/images/teams/Avani Pathak .jpg";
import Vivek from "../../../../assets/images/teams/Vivek ingle.jpg";
// import Suhas from "../../../../assets/images/teams/DSC_0292.jpg";
import Aditi from "../../../../assets/images/teams/Aditi Jadhav.jpg";
import Kunal from "../../../../assets/images/teams/Kunal Wagh.jpg";
// import Prajakta from "../../../../assets/images/teams/pra";
import Pratap from "../../../../assets/images/teams/img.jpg";
// import Sushrut from "../../../../assets/images/teams/Sushrut_Lekurwale_TeamPR.jpg";
// import SakshiAkhare from "../../../../assets/images/teams/IMG_7444";
import Atharva from "../../../../assets/images/teams/IMG_20230121_121344.jpg";
import Priyesh from "../../../../assets/images/teams/Priyesh.jpg";
import Arya from "../../../../assets/images/teams/Arya Malode.jpg";
import Pruthavirajsingh from "../../../../assets/images/teams/Pruthavirajsingh Dulat.jpg";
import Pradyumn from "../../../../assets/images/teams/pradyumn.jpeg.jpg";
import Kartik from "../../../../assets/images/teams/IMG_20230717_123512.jpg";
import Swetal from "../../../../assets/images/teams/Swetal.jpg";
import Aakanksha from "../../../../assets/images/teams/IMG_20230821_142027149~5.jpg";
// import Aditya from "../../../../assets/images/teams/";

const data = [
  {
    "Sr. no.": "1",
    Name: "Aniket Chaudhari",
    Designation: "President",
    img: Aniket,
    Team: "",
    "Contact number": "9511248614",
    "Email address": "aniketchuadhari303@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/aniket-chaudhari-801015217",
    "GitHub (optional)": "https://github.com/aniketchaudharicodes",
    "Twitter (optional )": "",
    "Instagram ": "https://instagram.com/aniketchaudhari.eth",
  },
  {
    "Sr. no.": "2",
    Name: "Sakshi Bajaj",
    Designation: "Vice President",
    img: Sakshi,
    Team: "",
    "Contact number": "7385051085",
    "Email address": "sakshibajaj393@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "S",
    LinkedIn: "https://www.linkedin.com/in/sakshi-bajaj-501494216",
    "GitHub (optional)": "https://github.com/bajajsakshi738",
    "Twitter (optional )": "https://twitter.com/bajajsakshi_85",
    "Instagram ": "https://instagram.com/iamsakshibajaj ",
  },
  {
    "Sr. no.": "3",
    Name: "Parth Inamdar",
    Designation: "Head",
    img: Parth,
    Team: "Technical",
    "Contact number": "8793928040",
    "Email address": "parthinamdar1970@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/parth-inamdar-81481a21b/",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "4",
    Name: "Ayush Chaudhari ",
    Designation: "Member",
    img: Aniket,
    Team: "",
    "Contact number": "9325898195",
    "Email address": "ayushschaudhari1904@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "XL",
    LinkedIn: "https://www.linkedin.com/in/ayush-chaudhari-14981623b",
    "GitHub (optional)": "https://github.com/the-bokya",
    "Twitter (optional )": "",
    "Instagram ": "https://www.instagram.com/thebokya/",
  },
  {
    "Sr. no.": "5",
    Name: "Hemant Singh Parmar",
    Designation: "Member",
    img: Hemant,
    Team: "",
    "Contact number": "7559228490",
    "Email address": "anmolpawar877@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "XL",
    LinkedIn: "https://www.linkedin.com/in/hemant-singh-parmar-b615a921a/",
    "GitHub (optional)": "https://github.com/hemant-code625",
    "Twitter (optional )": "https://twitter.com/ThisIs_Hemant",
    "Instagram ": "https://www.instagram.com/its_hemantsig/",
  },
  {
    "Sr. no.": "6",
    Name: "Suraj Nagre ",
    Designation: "Member",
    img: Suraj,
    Team: "",
    "Contact number": "7558697774",
    "Email address": "surajnagre30@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "XL",
    LinkedIn: "https://www.linkedin.com/in/suraj-nagre-836576214/",
    "GitHub (optional)": "https://github.com/kurai-sx",
    "Twitter (optional )": "https://twitter.com/Suraj_Nagre_",
    "Instagram ": "https://www.instagram.com/kurai.sx/",
  },
  {
    "Sr. no.": "7",
    Name: "Pratik Jadhav",
    Designation: "Member",
    img: Pratik,
    Team: "",
    "Contact number": "9404730294",
    "Email address": "j.pratik025@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/pratik-jadhav-44005a253/",
    "GitHub (optional)": "https://github.com/pratik50",
    "Twitter (optional )": "",
    "Instagram ": "https://www.instagram.com/j_pratik99/",
  },
  {
    "Sr. no.": "8",
    Name: "Parth Bhawar",
    img: ParthBhawar,
    Designation: "Member",
    Team: "",
    "Contact number": "9373097450",
    "Email address": "parthmgmu@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "9",
    Name: "Shashank Padhye",
    Designation: "Head",
    img: Aniket,
    Team: "Events",
    "Contact number": "9356425499",
    "Email address": "shashankpadhye9@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "10",
    Name: "Avani Pathak ",
    Designation: "Member",
    img: Avani,
    Team: "",
    "Contact number": "9021999704",
    "Email address": "pathakavani0226@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "L",
    LinkedIn: "https://www.linkedin.com/in/avani-pathak-5a131223b",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "https://instagram.com/__avaanniii__",
  },
  {
    "Sr. no.": "11",
    Name: "Vivek Ingle",
    Designation: "Member",
    img: Vivek,
    Team: "",
    "Contact number": "9529743301",
    "Email address": "vivekingle315@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/inglevivek/",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "https://www.instagram.com/thevivekingle/",
  },
  {
    "Sr. no.": "12",
    Name: "Suhas Magar",
    Designation: "Member",
    img: Aniket,
    Team: "",
    "Contact number": "7020463624",
    "Email address": "suhasmagar273@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/suhas-magar-46685a229/",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "https://www.instagram.com/suhas_m1/",
  },
  {
    "Sr. no.": "13",
    Name: "Aditi Jadhav",
    Designation: "Member",
    img: Aditi,
    Team: "",
    "Contact number": "7773923224",
    "Email address": "jadhavaditi126@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "S",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "14",
    Name: "Kunal Wagh",
    Designation: "Member",
    img: Kunal,
    Team: "",
    "Contact number": "9822634213",
    "Email address": "kunalwagh282@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "15",
    Name: "Prajakta Wakhare",
    Designation: "Head",
    img: Aniket,
    Team: "Design",
    "Contact number": "8055860877",
    "Email address": "wakhareprajakta@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "S",
    LinkedIn: "https://www.linkedin.com/in/prajakta-wakhare-00595b222",
    "GitHub (optional)": "https://github.com/Prajakta-Wakhare",
    "Twitter (optional )": "",
    "Instagram ": "https://instagram.com/praajakttaaa?utm_source=qr&igshid=MThlNWY1MzQwNA==",
  },
  {
    "Sr. no.": "16",
    Name: "Pratap Pawar",
    Designation: "Member",
    img: Pratap,
    Team: "",
    "Contact number": "9309058717",
    "Email address": "pratapsingh08pawar@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },

  {
    "Sr. no.": "19",
    Name: "Sushrut Lekurwale",
    img: Aniket,
    Designation: "Head",
    Team: "Public Relations ",
    "Contact number": "7768882081",
    "Email address": "lekurwalesushrut@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/sushrut-lekurwale/",
    "GitHub (optional)": "https://github.com/sushrutlekurwale",
    "Twitter (optional )": "",
    "Instagram ": "https://www.instagram.com/lekurwale_sushrut07/",
  },
  {
    "Sr. no.": "20",
    Name: "Sakshi Akhare",
    Designation: "Member",
    img: Aniket,
    Team: "",
    "Contact number": "9921096415",
    "Email address": "sakshiakhare17@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "S",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "21",
    Name: "Atharva Raulwar",
    Designation: "Member",
    img: Atharva,
    Team: "",
    "Contact number": "7507975334",
    "Email address": "atharvateamxtreme@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "22",
    Name: "Priyesh Sahijwani ",
    Designation: "Member",
    img: Priyesh,
    Team: "",
    "Contact number": "9890532718",
    "Email address": "priyeshsahijwani@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "",
    LinkedIn: "www.linkedin.com/in/priyesh-sahijwani",
    "GitHub (optional)": "https://github.com/priyesh-sahijwani",
    "Twitter (optional )": "",
    "Instagram ": "https://instagram.com/priyesh_sahijwani",
  },
  {
    "Sr. no.": "23",
    Name: "Arya Malode",
    Designation: "Head",
    img: Arya,
    Team: "Social Media",
    "Contact number": "8767467058",
    "Email address": "aryamalode17@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "XS",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "24",
    Name: "Pruthavirajsingh Dulat",
    Designation: "Member",
    img: Pruthavirajsingh,
    Team: "",
    "Contact number": "8793879208",
    "Email address": "pruthvirajytube@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "L",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "25",
    Name: "Pradyumn Bhanegaonkar ",
    Designation: "Member",
    img: Pradyumn,
    Team: "",
    "Contact number": "9422886711",
    "Email address": "pradyumnbhanegaonkar@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "L",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "26",
    Name: "Kartik Mhaske",
    Designation: "Head",
    img: Kartik,
    Team: "Marketing",
    "Contact number": "9130373357",
    "Email address": "Kartik69personal@gmail.com ",
    "T-shirt size (S/M/L/XL/XXL)": "M",
    LinkedIn: "https://www.linkedin.com/in/kartik-mhaske-1b36a0200",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "https://instagram.com/kartikmhaske_/",
  },
  {
    "Sr. no.": "27",
    Name: "Swetal Matkar",
    Designation: "Member",
    img: Swetal,
    Team: "",
    "Contact number": "8007773577",
    "Email address": "Matkarswetal@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "S",
    LinkedIn: "",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "",
  },
  {
    "Sr. no.": "28",
    Name: "Aakanksha Kate",
    Designation: "Member",
    img: Aakanksha,
    Team: "",
    "Contact number": "9168839562",
    "Email address": "aakankshakate29@gmail.com ",
    "T-shirt size (S/M/L/XL/XXL)": "S",
    LinkedIn: "https://www.linkedin.com/in/aakanksha-kate-a90994258/",
    "GitHub (optional)": "",
    "Twitter (optional )": "",
    "Instagram ": "https://www.instagram.com/itsme_ansha/",
  },
  {
    "Sr. no.": "29",
    Name: "Aditya Isadkar",
    Designation: "Member",
    img: Aniket,
    Team: "",
    "Contact number": "9403412529",
    "Email address": "adityaisadkar940@gmail.com",
    "T-shirt size (S/M/L/XL/XXL)": "XL",
    LinkedIn: "https://www.linkedin.com/in/aditya-isadkar-b73a02258",
    "GitHub (optional)": "https://github.com/adityaisadkar",
    "Twitter (optional )": "https://twitter.com/adirocks940",
    "Instagram ": "https://www.instagram.com/adi940rocks/",
  },
];

export default data;
